name: Pull locales

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  pull-locales:
    name: Pull locales
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout docs
        with:
          path: docs
      - uses: actions/checkout@v3
        name: Checkout locales
        with:
          path: locales
          repository: boticord/localization
      - name: Copy files
        run: |
          rm -r ./docs/locale
          cp -r ./locales/docs ./docs/locale
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Push changes
        with:
          repository: frontend
          commit_message: 'chore: pull locales'
          commit_user_name: BoticordAC
          commit_user_email: bc@livixx.me
          commit_author: BoticordAC <bc@livixx.me>
